export const ACTION_TYPE = {
    LOAD_MORE: "LOAD_MORE",
    REFRESH: "REFRESH",
    START_LOAD_MORE: "START_LOAD_MORE",
    END_LOAD_MORE: "END_LOAD_MORE",
    START_REFRESH: "START_REFRESH",
    END_REFRESH: "END_REFRESH",
}